CREATE TABLE ARCHIVO (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    PATH VARCHAR(50),
    SESION_ID INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT FK_archivo_sesion FOREIGN KEY (SESSION_ID) REFERENCES SESION(ID)
);

