CREATE TABLE DISPONIBILIDADHORARIA (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    INICIO TIMESTAMP,
    FIN TIMESTAMP,
    PROFESIONAL_DNI INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_disponibilidad_profesional FOREIGN KEY (PROFESIONAL_DNI) REFERENCES PERSONA(DNI)
);

