CREATE TABLE SESION (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    INICIO TIMESTAMP,
    FIN TIMESTAMP,
    NOTAS VARCHAR(255),
    PRACTICAPROFESIONAL_ID INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT FK_practica_sesion FOREIGN KEY (PRACTICAPROFESIONAL_ID) REFERENCES PRACTICAPROFESIONAL(ID)
);

