CREATE TABLE TURNO (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    START TIMESTAMP,
    END TIMESTAMP,
    CONFIRMADO VARCHAR(255),
    PRACTICAPROFESIONAL INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT FK_practica_turno FOREIGN KEY (PRACTICAPROFESIONAL) REFERENCES PRACTICAPROFESIONAL(ID)
);

