CREATE TABLE TURNO (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    INICIO TIMESTAMP,
    FIN TIMESTAMP,
    CONFIRMADO VARCHAR(255),
    PRACTICAPROFESIONAL_ID INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT FK_practica_turno FOREIGN KEY (PRACTICAPROFESIONAL_ID) REFERENCES PRACTICAPROFESIONAL(ID)
);

