CREATE TABLE USUARIO (
    CLAVEENCRIPTADA VARCHAR(50),
    PERSONA_DNI INTEGER NOT NULL,
    TYPE TINYINT(1),
    PRIMARY KEY (PERSONA_DNI),
    CONSTRAINT FK_usuario_dni FOREIGN KEY (PERSONA_DNI) REFERENCES PERSONA(DNI)
);
